[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokens = { workspace = true }
thiserror = { workspace = true }
statement = { workspace = true }